/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *@version 2
 * @author Juan Carlos Uscanga, Giancarlo De la Rosa, Abrahan Martinez, Pedro Yosue, Raul Lopez 
 */

    /**
     * <pre>
     * Clase Interfaz
     * 
     * Contiene la interfaz utilizada para generar la vista de la Calculadora,
     * En ella se contiene todos los botones que tendran utilidad para el funcionamiento de dicha calculadora.
     * </pre>
     */
    
    
public class Interfaz extends javax.swing.JFrame {


    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPantalla = new javax.swing.JTextField();
        jBotonSuma = new javax.swing.JButton();
        jBotonMultiplicacion = new javax.swing.JButton();
        jBotonDivision = new javax.swing.JButton();
        jBotonLimpiar = new javax.swing.JButton();
        jBotonResta = new javax.swing.JButton();
        jBoton7 = new javax.swing.JButton();
        jBoton8 = new javax.swing.JButton();
        jBoton9 = new javax.swing.JButton();
        jBotonParentesisAbre = new javax.swing.JButton();
        jBoton4 = new javax.swing.JButton();
        jBoton5 = new javax.swing.JButton();
        jBoton6 = new javax.swing.JButton();
        jBotonParentesisCierra = new javax.swing.JButton();
        jBoton1 = new javax.swing.JButton();
        jBoton2 = new javax.swing.JButton();
        jBoton3 = new javax.swing.JButton();
        jBotonPunto = new javax.swing.JButton();
        jBoton0 = new javax.swing.JButton();
        jBotonIgual = new javax.swing.JButton();
        jBotonPunto1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPantalla.setEditable(false);
        jPantalla.setBackground(new java.awt.Color(189, 228, 167));
        jPantalla.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPantallaActionPerformed(evt);
            }
        });

        jBotonSuma.setBackground(new java.awt.Color(191, 197, 191));
        jBotonSuma.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBotonSuma.setText("+");
        jBotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSumaActionPerformed(evt);
            }
        });

        jBotonMultiplicacion.setBackground(new java.awt.Color(191, 197, 191));
        jBotonMultiplicacion.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBotonMultiplicacion.setText("X");
        jBotonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonMultiplicacionActionPerformed(evt);
            }
        });

        jBotonDivision.setBackground(new java.awt.Color(191, 197, 191));
        jBotonDivision.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBotonDivision.setText("/");
        jBotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonDivisionActionPerformed(evt);
            }
        });

        jBotonLimpiar.setBackground(new java.awt.Color(191, 197, 191));
        jBotonLimpiar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBotonLimpiar.setText("A.C");
        jBotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLimpiarActionPerformed(evt);
            }
        });

        jBotonResta.setBackground(new java.awt.Color(191, 197, 191));
        jBotonResta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBotonResta.setText("-");
        jBotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonRestaActionPerformed(evt);
            }
        });

        jBoton7.setBackground(new java.awt.Color(191, 197, 191));
        jBoton7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton7.setText("7");
        jBoton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton7ActionPerformed(evt);
            }
        });

        jBoton8.setBackground(new java.awt.Color(191, 197, 191));
        jBoton8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton8.setText("8");
        jBoton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton8ActionPerformed(evt);
            }
        });

        jBoton9.setBackground(new java.awt.Color(191, 197, 191));
        jBoton9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton9.setText("9");
        jBoton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton9ActionPerformed(evt);
            }
        });

        jBotonParentesisAbre.setBackground(new java.awt.Color(191, 197, 191));
        jBotonParentesisAbre.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBotonParentesisAbre.setText("(");
        jBotonParentesisAbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonParentesisAbreActionPerformed(evt);
            }
        });

        jBoton4.setBackground(new java.awt.Color(191, 197, 191));
        jBoton4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton4.setText("4");
        jBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton4ActionPerformed(evt);
            }
        });

        jBoton5.setBackground(new java.awt.Color(191, 197, 191));
        jBoton5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton5.setText("5");
        jBoton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton5ActionPerformed(evt);
            }
        });

        jBoton6.setBackground(new java.awt.Color(191, 197, 191));
        jBoton6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton6.setText("6");
        jBoton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton6ActionPerformed(evt);
            }
        });

        jBotonParentesisCierra.setBackground(new java.awt.Color(191, 197, 191));
        jBotonParentesisCierra.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBotonParentesisCierra.setText(")");
        jBotonParentesisCierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonParentesisCierraActionPerformed(evt);
            }
        });

        jBoton1.setBackground(new java.awt.Color(191, 197, 191));
        jBoton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton1.setText("1");
        jBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton1ActionPerformed(evt);
            }
        });

        jBoton2.setBackground(new java.awt.Color(191, 197, 191));
        jBoton2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton2.setText("2");
        jBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton2ActionPerformed(evt);
            }
        });

        jBoton3.setBackground(new java.awt.Color(191, 197, 191));
        jBoton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton3.setText("3");
        jBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton3ActionPerformed(evt);
            }
        });

        jBotonPunto.setBackground(new java.awt.Color(191, 197, 191));
        jBotonPunto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBotonPunto.setText(".");
        jBotonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonPuntoActionPerformed(evt);
            }
        });

        jBoton0.setBackground(new java.awt.Color(191, 197, 191));
        jBoton0.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBoton0.setText("0");
        jBoton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton0ActionPerformed(evt);
            }
        });

        jBotonIgual.setBackground(new java.awt.Color(191, 197, 191));
        jBotonIgual.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jBotonIgual.setText("=");
        jBotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonIgualActionPerformed(evt);
            }
        });

        jBotonPunto1.setBackground(new java.awt.Color(191, 197, 191));
        jBotonPunto1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jBotonPunto1.setText("+/-");
        jBotonPunto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonPunto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jBoton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBoton8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBoton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBotonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBoton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBoton6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonParentesisAbre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBoton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonParentesisCierra, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBoton0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonPunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBoton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBoton8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBoton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoton6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonParentesisAbre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonParentesisCierra, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBotonPunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBoton0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBotonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton1ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "1"); 
    }//GEN-LAST:event_jBoton1ActionPerformed

    private void jBoton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton0ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "0"); 
    }//GEN-LAST:event_jBoton0ActionPerformed

    private void jBotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonRestaActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "-"); 
    }//GEN-LAST:event_jBotonRestaActionPerformed

    private void jBotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSumaActionPerformed
        // TODO add your handling code here:
        jPantalla.setText(jPantalla.getText() + "+");    
    }//GEN-LAST:event_jBotonSumaActionPerformed

    private void jBoton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton9ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "9"); 
    }//GEN-LAST:event_jBoton9ActionPerformed

    private void jBoton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton7ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "7"); 
    }//GEN-LAST:event_jBoton7ActionPerformed

    private void jBotonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonMultiplicacionActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "X"); 
    }//GEN-LAST:event_jBotonMultiplicacionActionPerformed

    private void jBotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDivisionActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "/"); 
    }//GEN-LAST:event_jBotonDivisionActionPerformed

    private void jBotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLimpiarActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(""); 
    }//GEN-LAST:event_jBotonLimpiarActionPerformed

    private void jBoton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton8ActionPerformed
        // TODO add your handling code here
         jPantalla.setText(jPantalla.getText() + "8"); 
    }//GEN-LAST:event_jBoton8ActionPerformed

    private void jBotonParentesisAbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonParentesisAbreActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "("); 
    }//GEN-LAST:event_jBotonParentesisAbreActionPerformed

    private void jBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton4ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "4"); 
    }//GEN-LAST:event_jBoton4ActionPerformed

    private void jBoton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton5ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "5"); 
    }//GEN-LAST:event_jBoton5ActionPerformed

    private void jBoton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton6ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "6"); 
    }//GEN-LAST:event_jBoton6ActionPerformed

    private void jBotonParentesisCierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonParentesisCierraActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + ")"); 
    }//GEN-LAST:event_jBotonParentesisCierraActionPerformed

    private void jBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton2ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "2"); 
    }//GEN-LAST:event_jBoton2ActionPerformed

    private void jBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton3ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "3"); 
    }//GEN-LAST:event_jBoton3ActionPerformed

    private void jBotonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonPuntoActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "."); 
    }//GEN-LAST:event_jBotonPuntoActionPerformed

    private void jPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPantallaActionPerformed

    private void jBotonPunto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonPunto1ActionPerformed
        // TODO add your handling code here:
         jPantalla.setText(jPantalla.getText() + "-"); 
         
    }//GEN-LAST:event_jBotonPunto1ActionPerformed

    private void jBotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonIgualActionPerformed
       String expresion= jPantalla.getText();
        String respuesta= Controlador.infijaAPostfija(expresion);
        jPantalla.setText(Controlador.evaluaPostfija(respuesta));
        
    }//GEN-LAST:event_jBotonIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBoton0;
    private javax.swing.JButton jBoton1;
    private javax.swing.JButton jBoton2;
    private javax.swing.JButton jBoton3;
    private javax.swing.JButton jBoton4;
    private javax.swing.JButton jBoton5;
    private javax.swing.JButton jBoton6;
    private javax.swing.JButton jBoton7;
    private javax.swing.JButton jBoton8;
    private javax.swing.JButton jBoton9;
    private javax.swing.JButton jBotonDivision;
    private javax.swing.JButton jBotonIgual;
    private javax.swing.JButton jBotonLimpiar;
    private javax.swing.JButton jBotonMultiplicacion;
    private javax.swing.JButton jBotonParentesisAbre;
    private javax.swing.JButton jBotonParentesisCierra;
    private javax.swing.JButton jBotonPunto;
    private javax.swing.JButton jBotonPunto1;
    private javax.swing.JButton jBotonResta;
    private javax.swing.JButton jBotonSuma;
    private javax.swing.JTextField jPantalla;
    // End of variables declaration//GEN-END:variables
}
